Repository facebookincubator/ptr, pull requests merged in 2019-12, with the labels that each got.

#80 Add support for passing --system-site-packages to venv
  ptr.py
  ptr_tests.py
Labels: CLA Signed

#81 Default to native recursive file search for black and flake8
  ptr.py
  ptr_tests.py
Labels: CLA Signed

#83 Add ability to create partial .ptrconfig files
  ptr.py
  ptr_tests.py
Labels: CLA Signed, enhancement

#85 Change coverage Data File Env Var for >= 5.0
  ptr.py
  ptr_tests.py
Labels: CLA Signed, bug

#86 Allow Windows to update pip + setuptools
  ptr.py
Labels: CLA Signed, bug

#87 Realphabetize command line arguments and update README
  README.md
  ptr.py
Labels: CLA Signed

#88 Realphabetize command line args
  README.md
  ptr.py
Labels: CLA Signed

#90 Move all .format() strs to f-string
  ci.py
  ptr.py
  ptr_tests.py
  ptr_tests_fixtures.py
Labels: CLA Signed, enhancement

#89 Coverage hack uneeded
  README.md
  ptr.py
  ptr_tests.py
  requirements.txt
Labels: CLA Signed
