Repository facebookincubator/ptr, pull requests merged in 2019-10, with the labels that each got.

#60 Handle OSX /private in coverage report
  ci.py
  ptr.py
  ptr_tests.py
  ptr_tests_fixtures.py
  setup.py
Labels: CLA Signed, bug

#65 Update README.md
  README.md
Labels: CLA Signed

#66 [ptr] Move CI to 3.8 offical + nightly
  .gitignore
  .travis.yml
  README.md
  ptr.py
  ptr_tests.py
Labels: CLA Signed, enhancement

#64 Add better handling for file not exists while in REQ_COV
  ptr.py
  ptr_tests.py
Labels: CLA Signed

#67 Fail when a non existent file has required coverage
  ptr.py
  ptr_tests.py
  ptr_tests_fixtures.py
Labels: CLA Signed, enhancement

#68 Add github action/workflow
  .github/workflows/pythonpackage.yml
  README.md
Labels: CLA Signed
