Repository facebookincubator/ptr, pull requests merged in 2019-11, with the labels that each got.

#69 Bug fix in atonce config param
  ptr.py
Labels: CLA Signed

#70 Fix actions config
  .github/workflows/pythonpackage.yml
  README.md
  ptr.py
Labels: CLA Signed, bug

#72 Remove deprecated setuptools `test` option
  ci.py
Labels: CLA Signed

#73 Run ptr even when test_suite is not provided
  ptr.py
  ptr_tests.py
Labels: CLA Signed

#74 Cleanup some _test_steps_runner tests copy pasta + refactor
  ptr_tests.py
Labels: CLA Signed, enhancement

#75 Add a release PyPI Upload Action
  .github/workflows/ci.yml
  .github/workflows/pypi_upload.yml
  README.md
Labels: CLA Signed, enhancement

#77 Add LICENSE to sdist + move to 2019.11.21 + update CHANGES.md
  CHANGES.md
  MANIFEST.in
  setup.py
Labels: CLA Signed, bug

#78 Run unit tests via coverage + add Python 3.8
  .coveragerc
  .github/workflows/ci.yml
  ptr_tests.py
  setup.cfg.sample
Labels: CLA Signed, enhancement
